# Generated by Django 2.1.4 on 2018-12-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181213_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=models.BinaryField(max_length=2000000, null=True),
        ),
    ]
