# Generated by Django 2.1.4 on 2019-01-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190113_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.BinaryField(max_length=20000000)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=models.BinaryField(max_length=4000000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Document'),
        ),
    ]
