name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  schedule:
    - cron:  '0 5 1 * *'
  workflow_dispatch: {}
  
env:
  IMAGE_NAME: djo-inventory

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/djoamersfoort/djo-inventory/djo-inventory:latest
          
      - name: Redeploy
        run: |
          curl https://portainer.djoamersfoort.nl/hooks/update-docker-image?stack=inventory_djoamersfoort_nl -H "X-Token: ${{ secrets.WEBHOOK_TOKEN }}"
      
      - name: Clean up old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'djo-inventory/djo-inventory'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
